# Generated by Django 5.1.6 on 2025-07-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('course', models.CharField(help_text="For JHS students: 'JHS'. For college: Track/Program (e.g., 'ICT', 'BSCS')", max_length=100)),
                ('year_level', models.PositiveSmallIntegerField(choices=[(7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12'), (1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year')])),
                ('screen_time', models.CharField(choices=[('<1h', 'Less than 1 hour'), ('1-3h', '1–3 hours'), ('3-5h', '3–5 hours'), ('5-7h', '5–7 hours'), ('>7h', 'More than 7 hours')], max_length=10)),
                ('duration_before_sleep', models.CharField(choices=[('no_use', "I don't use a device before sleeping"), ('<15m', 'Less than 15 minutes'), ('15-30m', '15–30 minutes'), ('30-60m', '30–60 minutes'), ('>60m', 'More than 1 hour')], max_length=10)),
                ('main_purpose', models.JSONField()),
                ('unintentional_use', models.CharField(choices=[('Never', 'Never'), ('Rarely', 'Rarely'), ('Sometimes', 'Sometimes'), ('Often', 'Often'), ('Always', 'Always')], max_length=10)),
                ('device_during_meals', models.CharField(choices=[('Never', 'Never'), ('Rarely', 'Rarely'), ('Sometimes', 'Sometimes'), ('Often', 'Often'), ('Always', 'Always')], max_length=10)),
                ('control_over_usage', models.PositiveSmallIntegerField()),
                ('device_while_studying', models.CharField(choices=[('Never', 'Never'), ('Rarely', 'Rarely'), ('Sometimes', 'Sometimes'), ('Often', 'Often'), ('Always', 'Always')], max_length=10)),
                ('device_upon_waking', models.BooleanField()),
                ('num_social_platforms', models.PositiveSmallIntegerField()),
                ('attempted_detox', models.BooleanField()),
                ('aware_of_screen_time', models.BooleanField()),
                ('usage_time', models.CharField(choices=[('morning (6am - 12pm)', 'Morning'), ('afternoon (12pm - 6pm)', 'Afternoon'), ('evening(6pm - 10pm)', 'Evening'), ('late_night(10pm - 3am)', 'Late Night'), ('throughout', 'Throughout the day')], max_length=25)),
                ('sleep_disruption', models.BooleanField()),
                ('predicted_qol', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
